### ISSUE TITLE
Unhandle expection

### ISSUE THREAD

**Issue by Taimoor-Teo2023** [microsoft/woodgrove-groceries#16]
![image](https://github.com/microsoft/woodgrove-groceries/assets/136562295/613a971d-d647-4ae4-867a-e4e8325fbd90)

**Comment by yoelhor** [comment]
Thanks @Taimoor-Teo2023  for your feedback. I tried and managed to reproduced issue. For me (at least) it happened when I sign-in with a Google of Facebook account, then deleted the account and try to sign-in using single sign-on session. Since the session is still exists (but invalid), so Entra ID returns an error back to the app indicating that the user doesn't exists.

**Comment by yoelhor** [comment]
I have added an authentication error page that shows how to handle such an error. 
![image](https://github.com/microsoft/woodgrove-groceries/assets/20111866/8a4e0b94-06d5-43e3-a596-d2ffd55265ba)
